name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  logger: ^2.5.0


flutter_native_splash:
  image: assets/images/Logo.png
  background_image: assets/images/Logo.png
  color: "#181B2C"
  android_12: true
  android: true
  ios: true

  # android_12:
  #   image: assets/images/Logo.png
  #   color: "#181B2C"
   

  web: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/font/
    - assets/icons/
